name: Release SDK
on:
  push:
    branches: main
    tags:
      - "v*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build rules
        run: ./gradlew jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/novu-kotlin.jar